run:
  go: "1.22"
  timeout: 10m
  tests: false
  allow-parallel-runners: true
linters-settings:
  funlen:
    lines: 200
    statements: 60
  cyclop:
    max-complexity: 20
    skip-tests: true
  gosec:
    exclude-generated: true
  lll:
    line-length: 200
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: false
  nestif:
    min-complexity: 7
  varnamelen:
    ignore-names:
      - err
      - wg
      - fs
      - id
      - vm
      - ns
      - ip

issues:
  exclude-dirs:
    - "./*/mock"
  exclude-files:
    - pkg/ocm/fakes/fakes.go
    - pkg/cache/fakes/cache.go
    - pkg/untar/untar.go
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
    - text: "should not use dot imports|don't use an underscore in package name"
      linters:
        - golint
    - source: "https://"
      linters:
        - lll
    - path: pkg/defaults/
      linters:
        - lll
    - path: _test\.go
      linters:
        - goerr113
        - gocyclo
        - errcheck
        - gosec
        - dupl
        - funlen
        - scopelint
        - testpackage
        - goconst
        - godox
    - path: internal/version/
      linters:
        - gochecknoglobals
    - path: internal/command/
      linters:
        - exhaustivestruct
        - lll
        - wrapcheck
    - source: "// .* #\\d+"
      linters:
        - godox
    - path: test/e2e/
      linters:
        - goerr113
        - gomnd
    # remove this once https://github.com/golangci/golangci-lint/issues/2649 is closed
    - path: /
      linters:
        - typecheck

linters:
  enable-all: true
  disable:
    - deadcode
    - depguard
    - exhaustivestruct
    - exhaustruct
    - forbidigo
    - gci
    - gochecknoglobals
    - gochecknoinits
    - godox
    - goerr113
    - golint
    - gomoddirectives
    - govet
    - ifshort
    - interfacer
    - ireturn
    - maligned
    - nilnil
    - nonamedreturns
    - nosnakecase
    - paralleltest
    - perfsprint
    - prealloc
    - scopelint
    - staticcheck
    - structcheck
    - tagliatelle
    - varcheck
    - varnamelen
    - wrapcheck
    - wsl
