version: "2"
run:
  go: "1.24"
  tests: false
  allow-parallel-runners: true
linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - funcorder
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gomoddirectives
    - iface
    - ireturn
    - nilnil
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - recvcheck
    - staticcheck
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 20
    funlen:
      lines: 200
      statements: 60
    lll:
      line-length: 200
    misspell:
      locale: US
    mnd:
      ignored-functions:
        - os.WriteFile
        - os.OpenFile
    nestif:
      min-complexity: 7
    nolintlint:
      require-explanation: true
      require-specific: false
      allow-unused: false
    varnamelen:
      ignore-names:
        - err
        - wg
        - fs
        - id
        - vm
        - ns
        - ip
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - golint
        text: should not use dot imports|don't use an underscore in package name
      - linters:
          - lll
        source: https://
      - linters:
          - lll
        source: ^// \+kubebuilder:*
      - linters:
          - lll
        path: pkg/defaults/
      - linters:
          - dupl
          - err113
          - errcheck
          - funlen
          - goconst
          - gocyclo
          - godox
          - gosec
          - scopelint
          - testpackage
        path: _test\.go
      - linters:
          - gochecknoglobals
        path: internal/version/
      - linters:
          - lll
          - wrapcheck
        path: internal/command/
      - linters:
          - godox
        source: '// .* #\d+'
      - linters:
          - err113
          - mnd
        path: test/e2e/
      - linters:
          - cyclop
        path: (.+)_test\.go
      - linters:
          - revive
        source: ginkgo|gomega
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - blank
        - dot
        - default
        - alias
        - localmodule
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
