apiVersion: v1
kind: Service
metadata:
  name: artifact-service
spec:
  type: ClusterIP
  selector:
    control-plane: controller-manager
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
