# permissions for end users to view snapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ocm-k8s-toolkit
    app.kubernetes.io/managed-by: kustomize
  name: snapshot-viewer-role
rules:
- apiGroups:
  - delivery.ocm.software
  resources:
  - snapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - delivery.ocm.software
  resources:
  - snapshots/status
  verbs:
  - get
