apiVersion: delivery.ocm.software/v1alpha1
kind: Component
metadata:
  namespace: default
  name: ocm-comp
spec:
  repositoryRef:
    namespace: default
    name: open-component-model-repo
  component: ocm.software/ocmcli
  downgradePolicy: Deny
  semver: ">= 6.1.x-0"
  semverFilter: ".*-rc.*"
  verify:
  - signature: ocm
    secretRef:
      name: ocm-pk-secret
  ocmConfig:
    - ref:
        apiVersion: v1
        kind: OCMRepository
        name: repo
  interval: 10m
  suspend: false
