apiVersion: delivery.ocm.software/v1alpha1
kind: Replication
metadata:
  labels:
    app.kubernetes.io/name: ocm-k8s-toolkit
    app.kubernetes.io/managed-by: kustomize
  name: replication-sample
spec:
  # TODO(user): Add fields here
