apiVersion: delivery.ocm.software/v1alpha1
kind: Replication
metadata:
  name: ocm-replication
  namespace: default
spec:
  componentRef:
    name: ocm-comp
    namespace: default
  ocmConfig:
    - kind: ConfigMap
      name: transfer-options
  interval: 10min
  targetRepositoryRef:
    name: ocm-repo
    namespace: default
