apiVersion: delivery.ocm.software/v1alpha1
kind: OCMRepository
metadata:
  namespace: default
  name: ocm-repo
spec:
  repositorySpec:
    baseUrl: ghcr.io/open-component-model
    type: OCIRegistry
  secretRefs:
  - name: ocm-secret
  configRefs:
  - name: ocm-config
  configSet: standard
  interval: 10m
  suspend: false
