apiVersion: delivery.ocm.software/v1alpha1
kind: OCMRepository
metadata:
  name: open-component-model-repo
spec:
  repositorySpec:
    baseUrl: ghcr.io/open-component-model
    type: OCIRegistry
  secretRef:
    name: pull-creds
  interval: 10m
