apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  namespace: default
  name: ocm-resource
spec:
  componentRef:
    namespace: default
    name: ocm-comp
  resourceSelector:
    resource:
      name: oci
    referencePath:
    - name: ocm-comp-ref
  secretRefs:
  - name: ocm-secret
  configRefs:
  - name: ocm-config
  configSet: standard
  interval: 10min
  suspend: false
