apiVersion: delivery.ocm.software/v1alpha1
kind: ResourceConfig
metadata:
  name: podinfo-config
spec:
  rules:
  - yamlsubst:
      source:
        value: Always
      target:
        file:
          path: deployment.yaml
          value: spec.template.spec.containers[0].imagePullPolicy
