apiVersion: v1
kind: ConfigMap
metadata:
  name: zot-config
data:
  # for docker compatibility, add '"http": { "compat": "docker2s2" }'
  config.json: |
    {
      "storage": {
        "rootDirectory": "/tmp/zot",
        "commit": true,
        "dedupe": true,
        "gc": true,
        "gcDelay": "1h",
        "gcInterval": "24h"
      },
      "http": {
        "address":"0.0.0.0",
        "port": "5000"
      },
      "log": {
          "level": "debug"
      }
    }