apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- service.yaml
images:
- name: zot-minimal
  newName: ghcr.io/project-zot/zot-minimal
  newTag: v2.1.2
