apiVersion: v1
kind: Service
metadata:
  name: zot-registry
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: zot
# ---
# Uncomment if you need an external port to the image registry
# Can be reached e.g. from the host with 'localhost:31000'
# apiVersion: v1
# kind: Service
# metadata:
#   name: zot-registry-external
# spec:
#   type: NodePort
#   ports:
#     - port: 5000
#       targetPort: 5000
#       nodePort: 31000
#   selector:
#     app: zot