apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ocm-k8s-toolkit-bootstrap-issuer
  namespace: ocm-k8s-toolkit-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ocm-k8s-toolkit-bootstrap-certificate
  namespace: ocm-k8s-toolkit-system
spec:
  # this is discouraged but required by ios
  commonName: cert-manager-ocm-tls
  isCA: true
  secretName: ocm-k8s-toolkit-registry-tls-certs
  subject:
    organizations:
      - ocm.software
  dnsNames:
    - ocm-k8s-toolkit-zot-registry.ocm-k8s-toolkit-system.svc.cluster.local
    - localhost
  ipAddresses:
    - 127.0.0.1
    - ::1
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  issuerRef:
    name: ocm-k8s-toolkit-bootstrap-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ocm-k8s-toolkit-certificate-issuer
  namespace: ocm-k8s-toolkit-system
spec:
  ca:
    secretName: ocm-k8s-toolkit-registry-tls-certs
