apiVersion: apps/v1
kind: Deployment
metadata:
  name: zot-registry
spec:
  template:
    spec:
      containers:
      - name: zot-registry
        volumeMounts:
        - name: zot-tls
          mountPath: /etc/zot/tls
          readOnly: true
      volumes:
      - name: zot-tls
        secret:
          secretName: ocm-k8s-toolkit-registry-tls-certs
# Registry is accessible in-cluster under:
# https://ocm-k8s-toolkit-zot-registry.ocm-k8s-toolkit-system.svc.cluster.local:5000/v2/_catalog
