apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certificate.yaml
- ../default
patches:
- path: zot-configmap-patch.yaml
- path: zot-deployment-patch.yaml
- path: mgr-deployment-patch.yaml
