apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certificate.yaml
- ../default
patches:
- path: configmap-patch.yaml
- path: deployment-patch.yaml
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/args/3
      value: --registry-insecure-skip-verify=false
  target:
    group: apps
    version: v1
    kind: Deployment
    name: controller-manager
