name: Check for diff after manifest and generated targets

on:
  pull_request: {}

permissions:
  contents: read
  pull-requests: write
   
jobs:
  diff-check-manifests:
    name: Check for diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: '${{ github.workspace }}/go.mod'
      - name: Restore Go cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: /home/runner/work/_temp/_github_home/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Lint
        run: make lint
      - name: Make manifests && generate
        run: |
          make manifests && make generate
      - name: go mod tidy
        run: |
          go mod tidy
      - name: Check for diff
        run: |
          gitStatus="$(git status --porcelain)"
          if [[ -z "${gitStatus}" ]]; then
              exit 0
          fi
          echo "${gitStatus}"
          exit 1
