name: publish image
on:
  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - '**/*.mod'
      - '**/*.sum'
      - 'config/**'
      - 'Dockerfile'
jobs:
  docker_publish:
    runs-on: large_runner
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        with:
          app_id: ${{ secrets.OCMBOT_APP_ID }}
          private_key: ${{ secrets.OCMBOT_PRIV_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - name: Docker Login
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: make
        run: make docker-buildx
        env:
          IMG: ghcr.io/${{ github.repository }}:latest
